//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSPS.Core.PluginSystem.Plugins.LiveRanking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UITemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMSPS.Core.PluginSystem.Plugins.LiveRanking.UITemplates", typeof(UITemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;frame posn=&quot;0 {[Y]} 0&quot;&gt;
        ///				&lt;quad sizen=&quot;1.6 1.6&quot; posn=&quot;-1.3 0 0.3&quot; style=&quot;Icons64x64_1&quot; substyle=&quot;ArrowGreen&quot;/&gt;
        ///				&lt;format textsize=&quot;1&quot; /&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;right&quot; posn=&quot;2.5 0 0.1&quot; text=&quot;{[Rank]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;left&quot; posn=&quot;2.8 0 0.1&quot; text=&quot;{[TimeOrScore]}&quot; textcolor=&quot;0D0F&quot;/&gt;
        ///				&lt;label sizen=&quot;8 2&quot; posn=&quot;7.2 0 0.1&quot; text=&quot;{[Nickname]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///			&lt;/frame&gt;.
        /// </summary>
        internal static string RankingHighlightTemplate {
            get {
                return ResourceManager.GetString("RankingHighlightTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;manialink id=&quot;{[ManiaLinkID]}&quot;&gt;
        ///	&lt;frame posn=&quot;48.5 15 0&quot;&gt;
        ///		&lt;!-- Start: Live Ranking Header --&gt;
        ///		&lt;quad sizen=&quot;11.5 2.5&quot; posn=&quot;5 0 0&quot; halign=&quot;left&quot; valign=&quot;top&quot; style=&quot;BgsPlayerCard&quot; substyle=&quot;BgActivePlayerName&quot;/&gt;
        ///		&lt;format textsize=&quot;1&quot;/&gt;
        ///		&lt;label posn=&quot;7 -0.5 2&quot; halign=&quot;left&quot; text=&quot;Live Rankings&quot;/&gt;
        ///		&lt;!-- End: Live Ranking Header --&gt;
        ///
        ///		&lt;!-- Top 3 Container --&gt;
        ///		&lt;quad sizen=&quot;16.7 6&quot; posn=&quot;0 -2.2 0&quot; halign=&quot;left&quot; valign=&quot;top&quot; style=&quot;Bgs1&quot; substyle=&quot;BgList&quot;/&gt;
        ///		
        ///		&lt;!-- Container for Records --&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RankingListTemplate {
            get {
                return ResourceManager.GetString("RankingListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;frame posn=&quot;0 {[Y]} 0&quot;&gt;
        ///				&lt;format textsize=&quot;1&quot;/&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;right&quot; posn=&quot;2.5 0 0.1&quot; text=&quot;{[Rank]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;left&quot; posn=&quot;2.8 0 0.1&quot; text=&quot;{[TimeOrScore]}&quot; textcolor=&quot;5AFF&quot;/&gt;
        ///				&lt;label sizen=&quot;8 2&quot; posn=&quot;7.2 0 0.1&quot; text=&quot;{[Nickname]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///			&lt;/frame&gt;.
        /// </summary>
        internal static string RankingTemplate {
            get {
                return ResourceManager.GetString("RankingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;frame posn=&quot;0 {[Y]} 0&quot;&gt;
        ///				&lt;format textsize=&quot;1&quot;/&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;right&quot; posn=&quot;2.5 0 0.1&quot; text=&quot;{[Rank]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///				&lt;label sizen=&quot;30 2&quot; halign=&quot;left&quot; posn=&quot;2.8 0 0.1&quot; text=&quot;{[TimeOrScore]}&quot; textcolor=&quot;DD0F&quot;/&gt;
        ///				&lt;label sizen=&quot;8 2&quot; posn=&quot;7.2 0 0.1&quot; text=&quot;{[Nickname]}&quot; textcolor=&quot;FFFF&quot;/&gt;
        ///			&lt;/frame&gt;.
        /// </summary>
        internal static string RankingTop3RecordTemplate {
            get {
                return ResourceManager.GetString("RankingTop3RecordTemplate", resourceCulture);
            }
        }
    }
}
