//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSPS.TestClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMSPS.TestClient.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;manialink&gt;
        ///  &lt;frame posn=&quot;-60 -10 5&quot;&gt;
        ///    &lt;label posn=&quot;25 -2 15&quot; sizen=&quot;40 4&quot; halign=&quot;center&quot; style=&quot;TextTitle3&quot; text=&quot;Input Window (Menu Mode)&quot;/&gt;
        ///    &lt;quad  posn=&quot;25 -1 10&quot; sizen=&quot;40 4&quot; halign=&quot;center&quot; style=&quot;Bgs1InRace&quot; substyle=&quot;BgTitle3_4&quot; manialink=&quot;http://funtrackers.bplaced.net/manialink/quad/index.php?type=classic&amp;amp;lang=en&amp;amp;x=inputx&amp;amp;y=inputy&quot;/&gt;
        ///    &lt;label posn=&quot;15   -6 5&quot; halign=&quot;center&quot; style=&quot;TextStaticSmall&quot; text=&quot;$o$ff0Position:&quot;/&gt;
        ///    &lt;la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManiaPage {
            get {
                return ResourceManager.GetString("ManiaPage", resourceCulture);
            }
        }
    }
}
