//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSPS.Core.PluginSystem.Plugins.Clock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UITemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMSPS.Core.PluginSystem.Plugins.Clock.UITemplates", typeof(UITemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;manialink id=&quot;{[ManiaLinkID]}&quot;&gt;
        ///	&lt;frame posn=&quot;-63.9 28.55 0&quot;&gt;
        ///		&lt;quad sizen=&quot;8.5 3.5&quot; style=&quot;Bgs1InRace&quot; substyle=&quot;NavButton&quot;/&gt;
        ///		&lt;quad sizen=&quot;3 3&quot; posn=&quot;0.2 -0.25 1&quot; style=&quot;BgRaceScore2&quot; substyle=&quot;ScoreReplay&quot; /&gt;
        ///		&lt;format textsize=&quot;2&quot;/&gt;
        ///		&lt;label posn=&quot;3.5 -0.75 2&quot; halign=&quot;left&quot; text=&quot;{[Hours2]}:{[Minutes2]}&quot;/&gt;
        ///	&lt;/frame&gt;
        ///&lt;/manialink&gt;.
        /// </summary>
        internal static string ClockTemplate {
            get {
                return ResourceManager.GetString("ClockTemplate", resourceCulture);
            }
        }
    }
}
