//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMSPS.Core.PluginSystem.Plugins.AdminPlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UITemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMSPS.Core.PluginSystem.Plugins.AdminPlayer.UITemplates", typeof(UITemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlayerListTemplate {
            get {
                return ResourceManager.GetString("PlayerListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;manialink id=&quot;{[ManiaLinkID]}&quot;&gt;
        ///	&lt;frame posn=&quot;-33.5 -45.6 0&quot;&gt;
        ///		&lt;quad sizen=&quot;12.9 2.5&quot; style=&quot;Bgs1InRace&quot; substyle=&quot;NavButton&quot;/&gt;
        ///		&lt;quad posn=&quot;1 -0.4 2&quot; sizen=&quot;1.7 1.7&quot; style=&quot;Icons64x64_1&quot; substyle=&quot;Refresh&quot; action=&quot;20101&quot;/&gt;
        ///		&lt;quad posn=&quot;4 -0.4 2&quot; sizen=&quot;1.7 1.8&quot; style=&quot;Icons64x64_1&quot; substyle=&quot;Camera&quot; action=&quot;20102&quot;/&gt;
        ///		&lt;quad posn=&quot;7 -0.4 2&quot; sizen=&quot;1.7 1.7&quot; style=&quot;Icons64x64_1&quot; substyle=&quot;ArrowLast&quot; action=&quot;20103&quot;/&gt;
        ///		&lt;quad posn=&quot;10.1 -0.4 2&quot; sizen=&quot;1.7 1.7&quot; style=&quot;Icons64x64_1&quot; substyle=&quot;IconPlayer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerTemplate {
            get {
                return ResourceManager.GetString("PlayerTemplate", resourceCulture);
            }
        }
    }
}
